---
- name: Install Web-server and upload files for Redhat/Debian
  hosts: all
  become: yes

  vars:
    source_file: ./my_website/index.html
    destin_file: /var/www/html

  tasks:
  - block:   # ===========Block for RedHat============
  
      - name: install Apache Server for RedHat
        yum: name=httpd state=installed

      - name: copy files in servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache Redhat

      - name: start and enable server
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block:   # ===========Block for Debian============
  
      - name: install Apache Server for Debian
        apt: name=apache2 state=latest

      - name: copy files in servers
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart Apache Debian

      - name: start and enable server Debian
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache Redhat
    service: name=httpd state=restarted
  
  - name: Restart Apache Debian
    service: name=apache2 state=restarted