---
- name: Redirecting task execution
  hosts: all
  become: yes
  
  vars:
   mytext: "Privet ot MAX"

  tasks: 
  - name: Ping test
    ping: 

  - name: Unregister Server from Load Balancer
    shell: echo This server {{ inventory_hostname }} was deregistered from our Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1

  - name: Create file1  #####Создание файла1
    copy: 
      dest: /home/file1.txt
      content: |
        This is FileN1
        On ENGLISH Hello Wold
        On RUSSIAN {{ mytext }}
    delegate_to: linux3

  - name: Create file2  #####Создание файла2
    copy: 
      dest: /home/file2.txt
      content: |
        This is FileN2
        On ENGLISH Hello Wold
        On RUSSIAN {{ mytext }}

  - name: Reboot my servers   ######Для перезапуска серверов
    shell: sleep 3 && reboot now  ####Подождать 3 секунды и отправить в ребут
    async: 1
    poll: 0  #####Закинуть sleep команды на сервера и забыть
 
  - name: Wait till my server will come up online
    wait_for:
        host: "{{ inventory_hostname }}"   ########Каких хостов запуск мы ждем
        state: started   ####чего мы ждем, чтоб стартовал
        delay: 5   ####Начинать считать после 5 секунд
        timeout: 40    ###максимум ждем 40 секунд
    delegate_to: 127.0.0.1
     


  


